exports.GET_ALL_DATA_PIXIV   = "SELECT * FROM pixiv"
exports.GET_LAST_ENTRY_PIXIV = "SELECT * FROM pixiv ORDER BY Id DESC LIMIT 1"
exports.GET_BY_ID_PIXIV      = "SELECT * FROM pixiv WHERE idPixiv = ? OR Id = ?"
exports.ADD_NEW_ENTRY_PIXIV  = "INSERT INTO pixiv (idPixiv,pixivName,Content,Quality,Favorite,Link) VALUES (?,?,?,?,?,?)"
exports.UPDATE_PIXIV         = "UPDATE pixiv SET idPixiv = ?,pixivName = ?, Content = ?,  Quality = ?, Favorite = ?, Link = ? WHERE Id = ?"

exports.GET_ALL_DATA_SAUCE = "SELECT * FROM sauces"
exports.GET_BY_ID_SAUCE    = "SELECT * FROM sauces WHERE id = ?"
exports.GET_BY_NAME_SAUCE  = "SELECT * FROM sauces WHERE Name LIKE ?"
exports.ADD_NEW_SAUCE      = "INSERT INTO sauces (Name, Viewed, Description, Comments, Link) VALUES (?,?,?,?,?)"
exports.UPDATE_SAUCE       = "UPDATE sauces SET Name = ?, Viewed = ?, Description = ?, Comments = ?, Link = ? WHERE id = ?"
exports.DELETE_SAUCE       = "DELETE FROM sauces WHERE id = ?"

exports.GET_ALL_DATA_ILLUSTRATORS  = "SELECT * FROM illustrators"
exports.GET_BY_ID_ILLUSTRATOR      = "SELECT * FROM illustrators WHERE Id = ?"
exports.GET_BY_SOURCE_ILLUSTRATOR  = "SELECT * FROM illustrators WHERE Source LIKE ?"
exports.GET_BY_NAME_ILLUSTRATOR    = "SELECT * FROM illustrators WHERE Name LIKE ?"
exports.ADD_ILLUSTRATOR            = "INSERT INTO illustrators (Name,Source,Content,Comments) VALUES (?,?,?,?)"
exports.UPDATE_ILLUSTRATOR         = "UPDATE illustrators SET Name = ?, Source = ?, Content = ?, Comments = ? WHERE Id = ?"
exports.DELETE_ILLUSTRATOR         = "DELETE FROM illustrators WHERE Id = ?"